# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicas: 1
  image: 660656973203.dkr.ecr.eu-west-1.amazonaws.com/spotify
  tag: latest

  containerPort: 8080
  resources:
    limits:
      cpu: 1000m
      memory: 750Mi
    requests:
      cpu: 250m
      memory: 256Mi
  livenessProbe:
    initialDelaySeconds: 25
    port: 8080
    path: spotify/v1/actuator
    failureThreshold: 1
    periodSeconds: 10

  readinessProbe:
    initialDelaySeconds: 25
    port: 8080
    path: spotify/v1/actuator
    failureThreshold: 1
    periodSeconds: 10

service:
  ports:
    port: 80
    targetPort: 8080
    nodePort: 30151
  type: NodePort

