server:
  servlet:
    context-path: /spotify/v1
  port: 8080

# Microservice Configuration
spring:
  application:
    name: Spotify

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:30007/spotify
    username: root
    password: password
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    properties.hibernate.show_sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    location: classpath:db/migration
    enabled: true
    driver: com.mysql.cj.jdbc.Driver
    schemas: spotify
    initialVersion: 0.0.0.0
    url: jdbc:mysql://localhost:30007/spotify?createDatabaseIfNotExist=true
    username: root
    password: password

management:
  endpoints:
    web:
      exposure:
        include: info,health

Spotify:
  resource:
    version: /v1
    endpoint1: { }
    endpoint2: { }

  error:
    codes:
      400: "Generic Bad Request Error"
      400-01: "First Custom Bad Request Error"
      404: "Generic Not Found Error"
      404-01: "First Custom Not Found Error"
      404-02: "First Custom Not Found Error"
      500: "Generic Internal Error"

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

springdoc:
  api-docs:
    enabled: true